"use client";

import { motion } from "framer-motion";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-background text-foreground overflow-x-hidden">
            <Header />
            <section className="pt-48 pb-32 px-8 md:px-24">
                <div className="container mx-auto max-w-4xl">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-12 border border-border bg-card shadow-2xl"
                    >
                        <h1 className="font-display font-black text-5xl uppercase tracking-tighter mb-12">Terms & Conditions</h1>
                        <div className="prose prose-invert prose-slate max-w-none space-y-6 text-foreground/60 font-sans leading-relaxed">
                            <p>1. This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
                            <p>2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name malabarchallengersfc.com (‘Website’), including the related mobile site and mobile application (hereinafter referred to as ‘Platform’).</p>
                            <p>3. The Platform is owned by MALABAR SPORTS AND RECREATION FOUNDATION, a company incorporated under the Companies Act, 1956 with its registered office at 18/1512 Rajeswari Compound Kalluthan Kadavu Road Puthiyara, Kozhikode – 673004, Kerala, INDIA.</p>
                            <p>4. Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.</p>
                            <p>5. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.</p>
                            <p>6. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Kozhikode and Kerala.</p>
                        </div>
                    </motion.div>
                </div>
            </section>
            <Footer />
        </main>
    );
}
